services:
  - type: web
    name: chatbot-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_APPS_SCRIPT_URL
        sync: false

  - type: web
    name: chatbot-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://chatbot-backend.onrender.com
